// 
// Copyright (c) 2025 Open Mail.dat
// 
// This source code is licensed under the MIT license found in the LICENSE file in the root directory of this source tree.
// 
// This code was auto-generated on May 27th, 2025.
// by the Open Mail.dat Code Generator.
// 
// Author: Daniel M porrey
// Version 25.1.0.2
// 

namespace Mail.dat
{
	/// <summary>
	/// Provides the header information that is present on the Certificate of Mailing Forms.
	/// </summary>
	public interface IChr : IMaildatEntity 
	{
		/// <summary>
		/// Job ID (CHR-1001)
		/// </summary>
		string JobID { get; set; }

		/// <summary>
		/// Certificate of Mailing Header ID (CHR-1002)
		/// Unique ID of the Certificate of Mailing Header Record.
		/// </summary>
		string CertificateOfMailingHeaderID { get; set; }

		/// <summary>
		/// Form Type (CHR-1101)
		/// </summary>
		string FormType { get; set; }

		/// <summary>
		/// Sender Tracking ID (CHR-1102)
		/// Unique ID generated by the sender.
		/// </summary>
		string SenderTrackingID { get; set; }

		/// <summary>
		/// Presort Mailing Job ID (CHR-1103)
		/// Job ID of Presort Mailing.
		/// </summary>
		string PresortMailingJobID { get; set; }

		/// <summary>
		/// Presort Mailing User License Code (CHR-1104)
		/// ULC documented in the Presort Mailing job referenced by Presort Mailing Job ID.  Must - begin with
		/// an alpha, be four characters, have no spaces, have no special characters, not be case sensitive.
		/// </summary>
		string PresortMailingUserLicenseCode { get; set; }

		/// <summary>
		/// Mail Owner Contact Name (CHR-1105)
		/// Ex: John Smith. Name of individual for contact support for this Form.
		/// </summary>
		string MailOwnerContactName { get; set; }

		/// <summary>
		/// Mail Owner Company Name (CHR-1106)
		/// Name of Organization that owns the records and the Form.
		/// </summary>
		string MailOwnerCompanyName { get; set; }

		/// <summary>
		/// Mail Owner Secondary Address (CHR-1107)
		/// Secondary Address of Organization that owns the records and the Form.
		/// </summary>
		string MailOwnerSecondaryAddress { get; set; }

		/// <summary>
		/// Mail Owner Primary Address (CHR-1108)
		/// Primary Address of Organization that owns the records and the Form.
		/// </summary>
		string MailOwnerPrimaryAddress { get; set; }

		/// <summary>
		/// Mail Owner City (CHR-1109)
		/// City of Organization that owns the records and the Form.
		/// </summary>
		string MailOwnerCity { get; set; }

		/// <summary>
		/// Mail Owner State (CHR-1110)
		/// State of Organization that owns the records and the Form. Required for addresses in the United
		/// States.
		/// </summary>
		string MailOwnerState { get; set; }

		/// <summary>
		/// Mail Owner Postal Code (CHR-1111)
		/// ZIP Code or Postal Code of Organization that owns the records and the Form. Left Justify; numeric
		/// values of the applicable 5-Digit, or 9-Digit, Barcode for the specific piece. If specifying a
		/// 5-digit barcode, then leave the rest of the field blank.
		/// </summary>
		string MailOwnerPostalCode { get; set; }

		/// <summary>
		/// Mail Owner Province or State - International (CHR-1112)
		/// Province or State of owner's address.  Applicable for international addresses.
		/// </summary>
		string MailOwnerProvinceOrStateInternational { get; set; }

		/// <summary>
		/// Mail Owner Country Code (CHR-1113)
		/// Country Code of owner's address.  When required populated with two-character ISO Country Code. Used
		/// for international addresses only.
		/// </summary>
		string MailOwnerCountryCode { get; set; }

		/// <summary>
		/// Mailing Date (CHR-1114)
		/// The date on which postage is paid to the USPS and verification is completed.
		/// </summary>
		DateOnly? MailingDate { get; set; }

		/// <summary>
		/// Certificate Status (CHR-1115)
		/// </summary>
		string CertificateStatus { get; set; }

		/// <summary>
		/// MPA ID (CHR-1116)
		/// Identify the permit paying for the Certificate of Mailing fees.
		/// </summary>
		string MPAID { get; set; }

		/// <summary>
		/// Verification Facility Name (CHR-1121)
		/// Name of Mailing Facility where verification occurs.
		/// </summary>
		string VerificationFacilityName { get; set; }

		/// <summary>
		/// Verification Facility ZIP Code (CHR-1122)
		/// ZIP Code of Post Office where postage statement will be finalized (the associated BMEU, not the
		/// DMU).
		/// </summary>
		string VerificationFacilityZIPCode { get; set; }

		/// <summary>
		/// Flex Option A (CHR-1117)
		/// Reserve Option.
		/// </summary>
		string FlexOptionA { get; set; }

		/// <summary>
		/// Flex Option B (CHR-1118)
		/// Reserve Option.
		/// </summary>
		string FlexOptionB { get; set; }

		/// <summary>
		/// Flex Option C (CHR-1119)
		/// Reserve Option.
		/// </summary>
		string FlexOptionC { get; set; }

		/// <summary>
		/// Reserve (CHR-1120)
		/// Reserved for future use.
		/// </summary>
		string ReserveCHR1120 { get; set; }

		/// <summary>
		/// CHR Record Status (CHR-2000)
		/// </summary>
		string CHRRecordStatus { get; set; }

		/// <summary>
		/// Closing Character (CHR-9999)
		/// Must be the # sign.
		/// </summary>
		string ClosingCharacter { get; }
	}
}